### ISSUE TITLE
'No such process' error

### ISSUE THREAD

**Issue by uludag** [JohnLonginotto/pybam#4]
```python
if self._subprocess.returncode is None:
    self._subprocess.kill()
```
Unless I add above if-statement in line 728(pybam.py), I get the following error:

> Exception OSError: (3, 'No such process') in <bound method read.__del__ of <lib.pybam.pybam.read instance at 0x3b1fcb0>> ignored

I found above workaround on the following documentation page:
https://docs.python.org/2.7/library/subprocess.html#subprocess.Popen.poll
which says 

> A `None` value indicates that the process hasn’t terminated yet

I was using Python 2.7.5 with Mixed Parser Example pattern given in the readme file

--mahmut

**Comment by JohnLonginotto** [comment]
Thank you for this fix mahmut, I will add your code to pybam immediately :)

I will also add the fix to lines 217 and 221 because in theory the same error could happen there if the user has a binary called pigz/gzip, but it for some reason immediately exits.
