### ISSUE TITLE
Letting you know

### ISSUE THREAD

**Issue by andyjslee** [JohnLonginotto/pybam#5]
File "pybam.py", line 265
    print 'PYBAM ERROR: Odd bzgip block detected! The author of pybam didnt think this would ever happen... please could you let me know?'

**Comment by JohnLonginotto** [comment]
Thank you Andy! That's really good to know.
Do you still have the BAM file that produces this? I would very much appreciate a sample to figure out what happened. Not the whole file - perhaps if you just do "head -c 1000000 ./the.bam > ./sample.bam" and then run sample.bam through pybam and see if it generates the error, then that 1Mb would be enough for me to get to the bottom of the error.

If it's not possible, then that's also OK - just knowing you got this message is enough to know i need to make an update to the internal python decompressor :)
