### ISSUE TITLE
how to write the alignment back to a bam?

### ISSUE THREAD

**Issue by crazyhottommy** [JohnLonginotto/pybam#8]
Hi John,
Is there a write function to write the record to a bam file?

This will not give a bam file
```python
for read in pybam.read('my.bam'):
        fout.write(read.bam)
```

Thanks!

**Comment by JohnLonginotto** [comment]
Have you also remembered to write out a valid BAM header first? 
```
bam = pybam.read('my.bam')
fout.write(bam.file_binary_header)
for read in bam: fout.write(read.bam)
```

Unfortunately the BAM format requires the header written in the same file as the data, before the data, because something something big-data something something cutting edge research, something something genomics.

**Comment by crazyhottommy** [comment]
thanks John.
